spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/ictdatabase?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8080